### ISSUE TITLE
breadcrumb is not updating as expected

### ISSUE THREAD

**Issue by AbhishekCompro** [sim5runner/sim5runner.github.io#14]
_From @AbhishekCompro on March 23, 2016 12:45_

_Copied from original issue: AbhishekCompro/abhishekcompro.github.io#58_

**Comment by AbhishekCompro** [comment]
_From @manishcompro on March 29, 2016 7:23_

Breadcrumb always show - Scenario T1 - Item 1 - Method 1 - Action 1.
It should only shows the node selected. If user has selected Method 1 in Left tree, it should show breadcrumb till Method 1.

**Comment by shiprabathla** [comment]
fixed

**Comment by shiprabathla** [comment]
Released
