### ISSUE TITLE
Issue in delete/add action coming due to data-tree not updated for action when method is deleted.

### ISSUE THREAD

**Issue by shiprabathla** [sim5runner/sim5runner.github.io#42]
Add a method. Make duplicate method. Delete first method. Second method becomes first method in tree. Now try deleting any action, not able to delete action

**Comment by shiprabathla** [comment]
There is another scenario:
1. Add two methods
2. Delete first
3. Now, there is only Method 1
4. Add action in Method 1 now
5. Error

Second Scenario:
1. Add three methods
2. Delete first
3. Now, there is Method 1 and Method 2
4. Add action in Method 1 now
5. It will add actions in Method 2

**Comment by AbhishekCompro** [comment]
Fixed, changed implementation from data tree.
