### ISSUE TITLE
NEW: Add 'ESC' in keyName list for pressKey action

### ISSUE THREAD

**Issue by piyush-mehta** [sim5runner/sim5runner.github.io#6]
Please add 'ESC' in keyName list for pressKey action. So that, ESC is shown in suggestions.

**Comment by shiprabathla** [comment]
Please use “SIM5ActionList.js” to edit SIM5 action list or key name list for the sim5runner tool.

**Comment by piyush-mehta** [comment]
Added 'ESC' keyname in master branch of sim5runner - SIM5ActionList.js
